# Generated by Django 4.1.5 on 2023-01-20 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_teacher_detail_alter_chapter_course_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='category',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='teacher',
            new_name='full_name',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='qualification',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='student',
            name='address',
        ),
        migrations.RemoveField(
            model_name='student',
            name='mobile_no',
        ),
    ]
