# Generated by Django 4.1.5 on 2023-01-20 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_rename_category_student_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='full_name',
        ),
    ]
