# Generated by Django 4.1.5 on 2023-01-20 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_student_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='fullname',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
