# Generated by Django 4.1.5 on 2023-01-24 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_notification'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'verbose_name_plural': '10. Notification'},
        ),
    ]
