# Generated by Django 4.1.5 on 2023-01-24 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_alter_notification_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='notif_text',
        ),
    ]
