# Generated by Django 4.1.5 on 2023-01-24 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_notification_notif_subject_notification_student_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notif_for',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
