# Generated by Django 4.1.5 on 2023-02-08 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0042_teacher_face_url_teacher_insta_url_teacher_twit_url_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
